In [1]:
import gym
import matplotlib.pyplot as plt
from gym.wrappers.pixel_observation import PixelObservationWrapper
from gym import ObservationWrapper
from gym.spaces import Box
import numpy as np

In [27]:
class GrayScaleObservation(ObservationWrapper):
    def __init__(self, env):
        super(GrayScaleObservation, self).__init__(env)

    def observation(self, observation):
        import cv2
        observation = cv2.cvtColor(observation['pixels'], cv2.COLOR_RGB2GRAY)
        return observation

In [7]:
# raw_env = RawPendulumEnv(g=9.81, biased=True, damping=1.0)
env = gym.make('Pendulum-v1', g=9.81)
env.reset()#如果不加这个reset会报错
env = PixelObservationWrapper(env,pixels_only=False)#返回的是一个字典
# env = GrayScaleObservation(env)
# print(state)
state = env.reset()
print(state['state'])
print(state['pixels'])
# plt.imshow(state['pixels'])

[-0.6017658  -0.7986726  -0.60086626]
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
