In [32]:
import torch
import numpy as np
#tensor type:torch.FloatTensor, torch.FloatTensor
#d type :torch.float32, torch.float64


#tensor的属性只有三个Tensor.dtype, Tensor.device, Torch.layout,Tensor.ndim

In [33]:
a = np.array([1.0,2.0],dtype = np.float)#float表示64位
b = torch.from_numpy(a)
print(a.dtype)
print(b.dtype)

a = np.array([1.0,2.0])#不指定类型默认64位float
b = torch.from_numpy(a)
print(a.dtype)
print(b.dtype)


a = np.array([1.0,2.0],dtype = np.float32)#32位
b = torch.from_numpy(a)
print(a.dtype)
print(b.dtype)



float64
torch.float64
float64
torch.float64
float32
torch.float32


In [34]:
c = b.float()#类型转换，神经网络的输入一般要求是float32，而numpy转换而来的一般是float64
print(c.dtype)

torch.float32


In [35]:
d = torch.tensor([2,3],dtype=torch.float64)
print(d.dtype)
d = torch.tensor([2,3],dtype=float)
print(d.dtype)
d = torch.tensor([2,3],dtype=torch.float32)
print(d.dtype)

d = torch.tensor([2,3],dtype=torch.float)#torch.float 表示32位，python中的float为64位
print(d.dtype)

d = torch.tensor([2.0,3])#不指定类型，如果有小数默认为float32，如果全是整数，默认为int64
print(d.dtype)

torch.float64
torch.float64
torch.float32
torch.float32
torch.float32


In [36]:
a = torch.tensor([1.0, 2])
b = torch.tensor([2.0, 2])
c = torch.Tensor.add(a,b)
print(c)
print(type(c))
print(c.dtype)#dtype是属性
print(c.device)#device是属性
print(c.ndim)#ndim属性
print(c.type())#type()是方法
print(c.t())#t是方法
print(c.T)#t是属性
print(c.amax())#t是方法


tensor([3., 4.])
<class 'torch.Tensor'>
torch.float32
cpu
1
torch.FloatTensor
tensor([3., 4.])
tensor([3., 4.])
tensor(4.)
