In [4]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data.sampler import SubsetRandomSampler,BatchSampler
from math import *
import networkx as nx

In [2]:
for i in (1,2,3),(4,5,6):
    print(i)

(1, 2, 3)
(4, 5, 6)


In [16]:
g=nx.Graph()
g.add_node(0,a=2)
g.nodes.data()

NodeDataView({0: {'a': 2}})

In [3]:
def MyFmod(_X,  _Y):
    return _X - (int)(_X / _Y) * _Y

def NormalizeAngle(angle):	
    if angle> 2.0*pi or angle < (-2.0*pi):
        a = MyFmod(angle + pi, 2.0 * pi)
        if a < 0.0 :
            a += 2.0 * pi
        return a - 2.0*pi
    else:
        return angle

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 11)

In [ ]:
NormalizeAngle(90)

In [5]:
a = np.random.randn(3,4,5)
a = a.reshape(1,-1)
print(a.shape)

(1, 60)


In [10]:
a = np.arange(10)
# a.resize(2,5)#就地修改
b=a.reshape(2,5)#先复制，再修改
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [3]:
a = np.array([[1, 2, 3],[7, 8, 9]])
a_list = [[1, 2, 3],[7, 8, 9]]
b = np.array([4, 5, 6])
# print(a[:][1][1])
# print(a_list[:][0])

In [11]:
ls = [[1,2,3],[4,5,7]]
ten = torch.tensor(ls,dtype=float)
# ten = torch.FloatTensor(ls)
print(ten.size())
print(ten.dtype)

torch.Size([2, 3])
torch.float32
