In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data.sampler import SubsetRandomSampler,BatchSampler

In [5]:
a = np.random.randn(3,4,5)
a = a.reshape(1,-1)
print(a.shape)

(1, 60)


In [10]:
a = np.arange(10)
# a.resize(2,5)#就地修改
b=a.reshape(2,5)#先复制，再修改
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [3]:
a = np.array([[1, 2, 3],[7, 8, 9]])
a_list = [[1, 2, 3],[7, 8, 9]]
b = np.array([4, 5, 6])
# print(a[:][1][1])
# print(a_list[:][0])

In [11]:
ls = [[1,2,3],[4,5,7]]
ten = torch.tensor(ls,dtype=float)
# ten = torch.FloatTensor(ls)
print(ten.size())
print(ten.dtype)

torch.Size([2, 3])
torch.float32
