In [23]:
import casadi
import numpy as np
from math import *

In [24]:
# OCDT相关参数及集合
Nfe = 10
K_radau = 3
I = np.arange(1,Nfe+1)
I1 = np.arange(1,Nfe)
J = np.arange(1,K_radau+1)
K = np.arange(0,K_radau+1)
tao = np.array([0, 0.1550510257216822, 0.6449489742783178, 1])
dljtauk = np.zeros((4,4))
dljtauk[0,:] = [-9.0000, 10.0488, -1.3821, 0.3333]
dljtauk[1,:] = [-4.1394, 3.2247, 1.1678, -0.2532]
dljtauk[2,:] = [1.7394, -3.5678, 0.7753, 1.0532]
dljtauk[3,:] = [-3, 5.5320, -7.5320, 5.0000]
dljtauk = dljtauk.transpose()
print(dljtauk)

[[-9.     -4.1394  1.7394 -3.    ]
 [10.0488  3.2247 -3.5678  5.532 ]
 [-1.3821  1.1678  0.7753 -7.532 ]
 [ 0.3333 -0.2532  1.0532  5.    ]]


In [25]:
#车辆自身参数
L_wheelbase = 2.8
a_max = 0.3
v_max = 2.0
phy_max = 0.72
w_max = 0.54

In [26]:
#决策变量
x = casadi.SX.sym('x', 11, 4)
y = casadi.SX.sym('y', 11, 4)
theta = casadi.SX.sym('theta', 11, 4)
v = casadi.SX.sym('v', 11, 4)
phy = casadi.SX.sym('phy', 11, 4)

a = casadi.SX.sym('a', 11, 4)
w = casadi.SX.sym('w', 11, 4)
tf = casadi.SX.sym('tf')
hi = casadi.SX.sym('hi')

X = casadi.reshape(x[1:,:],-1,1)
Y = casadi.reshape(y[1:,:],-1,1)
THETA = casadi.reshape(theta[1:,:],-1,1)
V = casadi.reshape(v[1:,:],-1,1)
PHY = casadi.reshape(phy[1:,:],-1,1)
A = casadi.reshape(a[1:,1:],-1,1)
W = casadi.reshape(w[1:,1:],-1,1)

In [27]:
temp_gx = dljtauk[0,1]*x[1,0] + dljtauk[1,1]*x[1,1] + dljtauk[2,1]*x[1,2] + dljtauk[3,1]*x[1,3] - hi*v[1,1]*cos(theta[1,1])
print(temp_gx)

(((((-4.1394*x_1)+(3.2247*x_12))+(1.1678*x_23))+(-0.2532*x_34))-(nan*(hi*v_12)))


In [28]:
#等式约束
g = []
gl = []
gu = []
for i in I:
    for k in J:
        temp_gx = dljtauk[0,k]*x[i,0] + dljtauk[1,k]*x[i,1] + dljtauk[2,K]*x[i,2] + dljtauk[3,K]*x[i,3] - hi*v[i,k]*cos(theta[i,k])
        g.append(temp_gx)

    # print(casadi.vertcat(*g).size())

# print(casadi.vertcat(*g).size())

In [40]:
aaa = np.arange(12).reshape(3,4)
print(aaa)
print(aaa[1:,:].transpose().reshape(-1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 4  8  5  9  6 10  7 11]


In [44]:
print(cos(0))
print(np.cos(0))

1.0
1.0
